prompt_file = "/home/kristen/LLMGuidedSeeding/prompts/ex_query.txt"
waypoint_threshold = 0.5
logging_directory = "experiment_data/"
commonObj_path = "/configs/commonObjs.txt"

common_ip = "40.78.49.78"

max_masks = 10 

[robot]
object_sever_url = "http://0.0.0.0:5005"
host_url = "http://0.0.0.0:5000"
frustrum_length = 20 
front_camera_fov_deg = 90 
down_cam_img_width = 640 
down_cam_img_height = 480
husky_length = 0.927
husky_width = 0.635
observation_frequency = 1
confidence_threshold = 0.75 
front_cam_intrinsics = [510.1259, 0.0, 420.6644, 0.0, 509.4401, 306.44069, 0.0, 0.0, 1.0]
right_cam_intrinsics = [496.36019, 0.0, 389.41303, 0.0, 495.20248, 301.6506, 0.0, 0.0, 1.0]
left_cam_intrinsics = [490.48909, 0.0, 413.2397, 0.0, 492.63605, 325.99985, 0.0, 0.0, 1.0]

[sensor_transforms]
left_down_camera_tf =  [0.1, 0.15,  0.5, 0.0, -1.571, 0.0] 
right_down_camera_tf = [0.1, -0.15, 0.5, 0.0, -1.571, 0.0]  
front_camera_tf = [0.152758, 0.0, 0.0324, 0.0, 0.0, 0.0] 
right_camera_tf = [0.0, -0.158258, 0.0324, 0.0, 0.0, -1.571]
left_camera_tf =  [0.0, 0.158248, 0.0324, 0.0, 0.0, 1.571]  
planter_tf = [-0.05, -0.1, 0.8, 0.0, 0.0, -1.571]

[tire_transforms] 
left_front_tire_tf =  [-0.165, 0.28,  0.8, 0.0, 0.0, 1.571]
right_front_tire_tf = [-0.165, -0.28, 0.8, 0.0, 0.0, -1.571]
left_back_tire_tf =   [-0.69,  0.28,  0.8, 0.0, 0.0, 1.571]
right_back_tire_tf =  [-0.69,  -0.28, 0.8, 0.0, 0.0, -1.571]
tire_length = 0.165 
tire_width = 0.114

[llm_model] 
model_name = "openai"
full_name = "gpt-4"
api_env_var = "openai_key"

[vqa_model]
full_name = "llava-1.5"
ip = "0.0.0.0"
port = 8000
temp = 0.8

[policyRehearsal] 
rehearsal_epochs = 10 

[simulation_parameters] 
sensor_range = 25 
miss_detection_rate = 0.15
measurement_var_x = 0.5 
measurement_var_y = 0.5
measurement_var_xy = 0.2