prompt_file = "/home/kristen/LLMGuidedSeeding/prompts/ex_query.txt"
waypoint_threshold = 0.5
logging_directory = "/home/kristen/LLMGuidedSeeding/experiment_data/"
commonObj_path = "/home/kristen/LLMGuidedSeeding/configs/commonObjs.txt"

common_ip = "40.78.49.78"

[robot]
object_sever_url = "http://0.0.0.0:5005"
host_url = "http://0.0.0.0:5000"
eps_dbscan = 0.5
min_samples = 5
median_filter_rate = 2
median_filtier_distance_threshold = 0.5
waypoint_threshold = 0.5

[llm_model] 
model_name = "openai"
full_name = "gpt-4"
api_env_var = "openai_key"

[vqa_model]
full_name = "llava-1.5"
ip = "0.0.0.0"
port = 8000
temp = 0.8

[policyRehearsal] 
rehearsal_epochs = 10